package ClientAndServer;


/**
* ClientAndServer/AlarmData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegOffice.idl
* Thursday, 13 April 2017 13:17:23 o'clock BST
*/

public final class AlarmData implements org.omg.CORBA.portable.IDLEntity
{
  public String aReading = null;
  public String alarm_source = null;

  public AlarmData ()
  {
  } // ctor

  public AlarmData (String _aReading, String _alarm_source)
  {
    aReading = _aReading;
    alarm_source = _alarm_source;
  } // ctor

} // class AlarmData
