package ClientAndServer;


/**
* ClientAndServer/HomeHubOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Camera.idl
* Thursday, 13 April 2017 15:23:09 o'clock BST
*/

public interface HomeHubOperations 
{

  // These operations return strings.
  String fetch_status ();
  String sensorHit ();
  String sendAlarm ();
  void sensorPanic ();
  void cameraPanic ();
  void sensorCancel ();
  void cameraCancel ();
  String currentImage ();
} // interface HomeHubOperations
