package ClientAndServer;

/**
* ClientAndServer/HomeHubHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Camera.idl
* Thursday, 13 April 2017 15:23:09 o'clock BST
*/

public final class HomeHubHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientAndServer.HomeHub value = null;

  public HomeHubHolder ()
  {
  }

  public HomeHubHolder (ClientAndServer.HomeHub initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientAndServer.HomeHubHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientAndServer.HomeHubHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientAndServer.HomeHubHelper.type ();
  }

}
