package ClientAndServer;


/**
* ClientAndServer/HomeHubPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Camera.idl
* Thursday, 13 April 2017 15:23:09 o'clock BST
*/

public abstract class HomeHubPOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.HomeHubOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fetch_status", new java.lang.Integer (0));
    _methods.put ("sensorHit", new java.lang.Integer (1));
    _methods.put ("submitAlarm", new java.lang.Integer (2));
    _methods.put ("sensorPanic", new java.lang.Integer (3));
    _methods.put ("cameraPanic", new java.lang.Integer (4));
    _methods.put ("sensorCancel", new java.lang.Integer (5));
    _methods.put ("cameraCancel", new java.lang.Integer (6));
    _methods.put ("currentImage", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // These operations return strings.
       case 0:  // ClientAndServer/HomeHub/fetch_status
       {
         String $result = null;
         $result = this.fetch_status ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientAndServer/HomeHub/sensorHit
       {
         String $result = null;
         $result = this.sensorHit ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ClientAndServer/HomeHub/submitAlarm
       {
         String $result = null;
         $result = this.sendAlarm ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClientAndServer/HomeHub/sensorPanic
       {
         this.sensorPanic ();
         out = $rh.createReply();
         break;
       }

       case 4:  // ClientAndServer/HomeHub/cameraPanic
       {
         this.cameraPanic ();
         out = $rh.createReply();
         break;
       }

       case 5:  // ClientAndServer/HomeHub/sensorCancel
       {
         this.sensorCancel ();
         out = $rh.createReply();
         break;
       }

       case 6:  // ClientAndServer/HomeHub/cameraCancel
       {
         this.cameraCancel ();
         out = $rh.createReply();
         break;
       }

       case 7:  // ClientAndServer/HomeHub/currentImage
       {
         String $result = null;
         $result = this.currentImage ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/HomeHub:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HomeHub _this() 
  {
    return HomeHubHelper.narrow(
    super._this_object());
  }

  public HomeHub _this(org.omg.CORBA.ORB orb) 
  {
    return HomeHubHelper.narrow(
    super._this_object(orb));
  }


} // class HomeHubPOA
