package ClientAndServer;


/**
* ClientAndServer/RegOfficePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegOffice.idl
* Thursday, 13 April 2017 13:17:23 o'clock BST
*/

public abstract class RegOfficePOA extends org.omg.PortableServer.Servant
 implements ClientAndServer.RegOfficeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sensorHit", new java.lang.Integer (0));
    _methods.put ("sensorPanic", new java.lang.Integer (1));
    _methods.put ("raiseAlarm", new java.lang.Integer (2));
    _methods.put ("registerUser", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClientAndServer/RegOffice/sensorHit
       {
         String $result = null;
         $result = this.sensorHit ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ClientAndServer/RegOffice/sensorPanic
       {
         this.sensorPanic ();
         out = $rh.createReply();
         break;
       }

       case 2:  // ClientAndServer/RegOffice/raiseAlarm
       {
         ClientAndServer.AlarmData anAlarm = ClientAndServer.AlarmDataHelper.read (in);
         this.raiseAlarm (anAlarm);
         out = $rh.createReply();
         break;
       }

       case 3:  // ClientAndServer/RegOffice/registerUser
       {
         String who = in.read_string ();
         String contact_details = in.read_string ();
         this.registerUser (who, contact_details);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClientAndServer/RegOffice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RegOffice _this() 
  {
    return RegOfficeHelper.narrow(
    super._this_object());
  }

  public RegOffice _this(org.omg.CORBA.ORB orb) 
  {
    return RegOfficeHelper.narrow(
    super._this_object(orb));
  }


} // class RegOfficePOA
