package ClientAndServer;


/**
* ClientAndServer/RegOfficeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RegOffice.idl
* Thursday, 13 April 2017 13:17:23 o'clock BST
*/

public interface RegOfficeOperations 
{
  String sensorHit ();
  void sensorPanic ();
  void raiseAlarm (ClientAndServer.AlarmData anAlarm);
  void registerUser (String who, String contact_details);
} // interface RegOfficeOperations
