package ClientAndServer;


/**
* ClientAndServer/StatusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Camera.idl
* Thursday, 13 April 2017 15:23:09 o'clock BST
*/

public interface StatusOperations 
{
  String message ();

String sensorHit();
} // interface StatusOperations
