package ClientAndServer;


/**
* ClientAndServer/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Camera.idl
* Thursday, 13 April 2017 15:23:09 o'clock BST
*/

abstract public class StatusHelper
{
  private static String  _id = "IDL:ClientAndServer/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientAndServer.Status that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientAndServer.Status extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ClientAndServer.StatusHelper.id (), "Status");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientAndServer.Status read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StatusStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientAndServer.Status value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ClientAndServer.Status narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientAndServer.Status)
      return (ClientAndServer.Status)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClientAndServer._StatusStub stub = new ClientAndServer._StatusStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ClientAndServer.Status unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ClientAndServer.Status)
      return (ClientAndServer.Status)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ClientAndServer._StatusStub stub = new ClientAndServer._StatusStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
